// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface ReserveBookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReserveBookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bookId = 1;</code>
   */
  java.lang.String getBookId();
  /**
   * <code>string bookId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBookIdBytes();

  /**
   * <code>string userId = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
