// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface ReserveBookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReserveBookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmationNumber = 1;</code>
   */
  java.lang.String getConfirmationNumber();
  /**
   * <code>string confirmationNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationNumberBytes();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
