// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface SearchBookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchBookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 1;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();
}
