// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface SearchBookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchBookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string author = 2;</code>
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 2;</code>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int32 year = 4;</code>
   */
  int getYear();

  /**
   * <pre>
   * I needed to add a variable when the server finishes of sending results of the search
   * </pre>
   *
   * <code>bool searchFinished = 5;</code>
   */
  boolean getSearchFinished();
}
