// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_LogInRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_LogInRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_LogInResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_LogInResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_updateProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_updateProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_updateProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_updateProfileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010service2\".\n\014LogInReque" +
      "st\022\014\n\004name\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\037\n\rLo" +
      "gInResponse\022\016\n\006status\030\001 \001(\t\"l\n\024updatePro" +
      "fileRequest\022\014\n\004name\030\001 \001(\t\022\020\n\010password\030\002 " +
      "\001(\t\022\016\n\006status\030\003 \001(\t\022\017\n\007address\030\004 \001(\t\022\023\n\013" +
      "phoneNumber\030\005 \001(\t\"\'\n\025updateProfileRespon" +
      "se\022\016\n\006status\030\001 \001(\t2\234\001\n\010Service2\022:\n\005LogIn" +
      "\022\026.service2.LogInRequest\032\027.service2.LogI" +
      "nResponse\"\000\022T\n\rupdateProfile\022\036.service2." +
      "updateProfileRequest\032\037.service2.updatePr" +
      "ofileResponse\"\000(\001B\035\n\013ds.service2B\014Servic" +
      "e2ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_LogInRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_LogInRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_LogInRequest_descriptor,
        new java.lang.String[] { "Name", "Password", });
    internal_static_service2_LogInResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_LogInResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_LogInResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_service2_updateProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_updateProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_updateProfileRequest_descriptor,
        new java.lang.String[] { "Name", "Password", "Status", "Address", "PhoneNumber", });
    internal_static_service2_updateProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_updateProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_updateProfileResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
