// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface updateProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.updateProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string status = 3;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string address = 4;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 4;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string phoneNumber = 5;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phoneNumber = 5;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();
}
