// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "Lights are turned on" or "Lights are turned off"
   * </pre>
   *
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * "Lights are turned on" or "Lights are turned off"
   * </pre>
   *
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
