// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * true to turn on the lights, false to turn off the lights
   * </pre>
   *
   * <code>bool turnOn = 1;</code>
   */
  boolean getTurnOn();
}
